version: "3"
services:
  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    networks:
      - jukebox
  api:
    build:
      context: ./backend
    ports:
      - "12345:12345"
    links:
      - db
    networks:
      - jukebox
    depends_on:
      - elasticsearch
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - jukebox
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - jukebox
    environment:
      - discovery.type=single-node
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    networks:
      - jukebox
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.jukebox.com
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  jukebox:
    driver: bridge
